# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
#title: "LIS: Legume Information System"
title: "PeanutBase"
#subtitle: Information about legume traits for crop improvement
subtitle: Genetic and genomic data to enable more rapid crop improvement in peanut.
logo: /assets/img/logo.png
favicon: /assets/icons/favicon.ico
email: sdash@ncgr.org
description: >- # this means to ignore newlines until "baseurl:"
  A collaborative, community resource to facilitate peanut improvement by integrating
  genetic, genomic, and trait data across Arachis species.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://dev.lis.ncgr.org:50053" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://peanutbase.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: peanutbaseorg #legumefed
github_username: peanutbase #legumeinfo
#google_analytics_id: "UA-49655154-2"
google_analytics_id: "G-EP8B1GVJKL"
newsletter: http://eepurl.com/cX_JjL
date_format: "%B %d, %Y"
# Set the LIS Datastore base URL here
datastoreurl: https://data.legumeinfo.org

card_item_limit: 5
#news_card_item_limit: 2
#events_card_item_limit: 3
#twitter_card_item_limit: 2

# Build settings
theme: jekyll-theme-legumeinfo
# Enable display of future Events
future: true
plugins:
  - jekyll-feed
  - jekyll-datapage-generator

# Pages to generate automatically
page_gen-dirs: false
page_gen:
- data: "germplasm_images"
  dir: "germplasm"
  name: "page_name"
  title: "name"
- data: "mas_traits"
  dir: "mas"
  name: "page_name"
  title: "name"
- data: taxon_list
  template: taxon
  dir: taxa
  name: genus
  index_files: true
  debug: true
- data: taxon_list
  template: collection
  dir: collections
  name: genus
  index_files: true
  debug: true

style:
    link_color: '#0071B3'
    link_hover_color: '#018fe2'
      #primary_background: '#87a96b'
    invert_navbar_text: true
    primary_background: '#31160B'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - docker-compose.yml
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
